# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  labo02:
    image: nathansegers/labo02-test
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SUPER_SECRET_PASSWORD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/aspnetapp.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./.aspnet/https:/certs
      - ./assets/CSV:/mnt/data
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourNewStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - ./db/data:/var/opt/mssql/data
